services:
  savapage:
    hostname: sp-server
    image: savapage
    container_name: savapage_savapage
    environment:
      - TZ=Europe/Berlin
      
      # --- Values from .env file (with Fallbacks) ---
      - SAVAPAGE_NS=${SAVAPAGE_NS:-SP_}
      - SP_CONTAINER=${SP_CONTAINER:-DOCKER}
      
      # App Config
      - SP_SRV_01=visitor.organization:My Company
      - SP_SRV_02=server.port:${SP_HTTP_PORT:-8631}
      
      # Database Config
      - SP_SRV_11=database.type:PostgreSQL
      - SP_SRV_12=database.driver:org.postgresql.Driver
      - SP_SRV_13=database.url:jdbc:postgresql://postgres:5432/${POSTGRES_DB:-savapage}
      - SP_SRV_14=database.user:${POSTGRES_USER:-savapage}
      - SP_SRV_15=database.password:${POSTGRES_PASSWORD:-savapage}
#   devices:
#     - /dev/bus/usb/004/004:/dev/bus/usb/004/004
    ports:
      - "${SP_CUPS_PORT:-631}:631"
      - "${SP_HTTP_PORT:-8631}:${SP_HTTP_PORT:-8631}"
    networks:
      - default
    depends_on:
      - postgres
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./init-savapage.sql:/docker-entrypoint-initdb.d/init.sql
      # Dynamic Storage Paths with Fallback to ./volumes
      - ${SP_STORAGE_PATH:-./volumes}/custom:/opt/savapage/server/custom
      - ${SP_STORAGE_PATH:-./volumes}/data:/opt/savapage/server/data
      - ${SP_STORAGE_PATH:-./volumes}/ext:/opt/savapage/server/ext
      - ${SP_STORAGE_PATH:-./volumes}/logs:/opt/savapage/server/logs
      - ${SP_STORAGE_PATH:-./volumes}/cups:/etc/cups
    restart: unless-stopped

  postgres:
    hostname: sp-postgres
    image: postgres:15-alpine
    container_name: savapage_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-savapage}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-savapage}
      - POSTGRES_DB=${POSTGRES_DB:-savapage}
    networks:
      - default
    volumes:
      # Dynamic Storage Path for Database with Fallback
      - ${SP_STORAGE_PATH:-./volumes}/database:/var/lib/postgresql/data
      # Initialization script
      - ./init-savapage.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

networks:
  default:
    name: docker_savapage_network
    driver: bridge
